version: '3.4'

services:
  cleanarchitecture.api:
    image: ${DOCKER_REGISTRY-}cleanarchitectureapi
    build:
      context: .
      dockerfile: CleanArchitecture.Api/Dockerfile
    ports:
      - 8081:8081
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://cleanarchitecture.dashboard:18889
    networks:
     - otel

  coffeeshop.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: dashboard
    ports:
     - 18888:18888
    networks:
     - otel

networks:
  otel: